### ISSUE TITLE
Add Function Documentation

### ISSUE THREAD

**Issue by cannin** [dfci/CellBox#43]
Add documentation to the following functions: 

- [ ] FuncA
- [ ] FuncB

**Comment by Mustardburger** [comment]
I have a question about the function cellbox.utils.md5 at line 71 in main.py. Why do we need this function?

**Comment by DesmondYuan** [comment]
Please take a look at the PR #47. Feel free to add comments / approve it if LGTM.

> I have a question about the function cellbox.utils.md5 at line 71 in main.py. Why do we need this function?

This was used when calling `prepare_workdir()` under `scripts/main.py`, which creates the working directory for each experiment and generates necessary files. This md5 string adds an unique identifier to each experiment we run as an affix to the filepath so that we can always keep the reference of each different config we have used.
